CASE DEFINITIONS ::= BEGIN


A OBJECT IDENTIFIER ::= { org 1 }
B OBJECT IDENTIFIER ::= { A 2 }

C OBJECT-TYPE
    SYNTAX INTEGER
    MAX-ACCESS read-only
    STATUS current
    DESCRIPTION
        "C"
    ::= { B 1 }

D OBJECT-TYPE
    SYNTAX INTEGER
    MAX-ACCESS read-only
    STATUS current
    DESCRIPTION
        "D"
    ::= { B 1 }  

ll ::= SEQUENCE {
    index   INTEGER,
    index1  INTEGER
}

END

