CASE DEFINITIONS ::= BEGIN

IMPORTS
    org FROM ALIALI;

A OBJECT IDENTIFIER ::= { org 1 }
B OBJECT IDENTIFIER ::= { A 2 }

C OBJECT-TYPE
    SYNTAX INTEGER
    MAX-ACCESS read-only
    STATUS current
    DESCRIPTION
        "C"
    ::= { B 1 }

END

