CASE DEFINITIONS ::= BEGIN

IMPORTS
    aliali FROM ALIALI;

sys OBJECT-TYPE
    SYNTAX INTEGER
    MAX-ACCESS read-only
    STATUS current
    DESCRIPTION
        "Just a case"
    ::= { aliali 1 }

END

